- include_vars: vars/logical_switch_state_dict.yml

- include_tasks: logical_switch/get.yml

- include_tasks: logical_switch/post.yml
  when:
    - "state is 'present'"

- include_tasks: logical_switch/put.yml
  when:
    - "state is 'present'"

- include_tasks: logical_switch/delete.yml
  when:
    - "state is 'absent'"
