- name: "logical_switch_get"
  uri:
    url: "{{ provider.connection }}://{{ provider.host }}:{{ provider.port }}/api/v1/logical-switches"
    username: "{{ provider.username }}"
    password: "{{ provider.password }}"
    method: GET
    status_code: 200
    body_format: json
    force_basic_auth: yes
    return_content: yes
    validate_certs: {{ validate_certs }}
    body: {}
  register: r_logical_switch_get

- set_facts:
    LogicalSwitchEntryExists: true
  loop: "{{ r_logical_switch_get.result.json.results | default([]) }}"
  loop_control:
    loop_var: logical_switch_entry
  when: logical_switch_entry.display_name == display_name
